# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keeps maturin for python builds up to date.
  - package-ecosystem: "pip"
    directory: "/rustoku-py"
    schedule:
      interval: "weekly"

  # Keeps npm packages for demo up to date.
  - package-ecosystem: "npm"
    directory: "/demo"
    schedule:
      interval: "weekly"
