version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      cargo-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      actions-dependencies:
        patterns:
          - '*'

  # Keeps maturin for python builds up to date.
  - package-ecosystem: 'pip'
    directory: '/rustoku-py'
    schedule:
      interval: 'monthly'
    groups:
      python-dependencies:
        patterns:
          - '*'

  # Keeps npm packages for demo up to date.
  - package-ecosystem: 'npm'
    directory: '/demo'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'rustoku-wasm'
      - dependency-name: 'typescript'
      - dependency-name: 'typescript-eslint'
    groups:
      demo-dependencies:
        patterns:
          - '*'

  # Keeps npm packages for wasm bindings up to date.
  - package-ecosystem: 'npm'
    directory: '/rustoku-wasm'
    schedule:
      interval: 'monthly'
    groups:
      wasm-dependencies:
        patterns:
          - '*'
